set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_SYSROOT $ENV{WASI_SDK_PATH}/share/wasi-sysroot/)
set(triple wasm32-wasi)

if(WIN32)
	set(WASI_HOST_EXE_SUFFIX ".exe")
else()
	set(WASI_HOST_EXE_SUFFIX "")
endif()

set(CMAKE_C_COMPILER           $ENV{WASI_SDK_PATH}/bin/clang${WASI_HOST_EXE_SUFFIX})
set(CMAKE_CXX_COMPILER         $ENV{WASI_SDK_PATH}/bin/clang++${WASI_HOST_EXE_SUFFIX})
set(CMAKE_AR                   $ENV{WASI_SDK_PATH}/bin/llvm-ar${WASI_HOST_EXE_SUFFIX})
set(CMAKE_RANLIB               $ENV{WASI_SDK_PATH}/bin/llvm-ranlib${WASI_HOST_EXE_SUFFIX})
set(CMAKE_C_COMPILER_TARGET    ${triple})
set(CMAKE_CXX_COMPILER_TARGET  ${triple})
